"use client";

import { useEffect, useState } from "react";
import { GuidelineRagCard, type GuidelineRagResult } from "../components/GuidelineRagCard";

type CorpusDoc = { doc_id: string; title: string; source: string; url?: string | null; n_chunks: number };

const EXAMPLES = [
  "First-line antibiotics for a healthy adult outpatient with community-acquired pneumonia?",
  "Which first-line drug classes are recommended for stage 2 hypertension?",
  "When should an SGLT2 inhibitor be preferred over a GLP-1 receptor agonist in type 2 diabetes?",
  "What is the first-line vasopressor and MAP target in septic shock?",
];

export default function GuidelineRagPage() {
  const [apiBase, setApiBase] = useState("http://127.0.0.1:8001");
  const [question, setQuestion] = useState(EXAMPLES[0]);
  const [topK, setTopK] = useState(4);
  const [externalEvidence, setExternalEvidence] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<GuidelineRagResult | null>(null);
  const [uploading, setUploading] = useState(false);
  const [indexInfo, setIndexInfo] = useState<string | null>(null);
  const [corpus, setCorpus] = useState<{ embed_model: string; n_docs: number; n_chunks: number; documents: CorpusDoc[] } | null>(null);
  const [showCorpus, setShowCorpus] = useState(true);

  async function loadCorpus() {
    try {
      const response = await fetch(`${apiBase.replace(/\/$/, "")}/api/v1/guideline/docs`);
      if (response.ok) setCorpus(await response.json());
    } catch {
      /* corpus list is best-effort */
    }
  }

  useEffect(() => {
    loadCorpus();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [apiBase]);

  async function uploadDoc(file: File) {
    setUploading(true);
    setError(null);
    setIndexInfo(null);
    try {
      const form = new FormData();
      form.append("file", file);
      const response = await fetch(`${apiBase.replace(/\/$/, "")}/api/v1/guideline/upload`, {
        method: "POST",
        body: form,
      });
      if (!response.ok) {
        throw new Error(`HTTP ${response.status}: ${await response.text()}`);
      }
      const data = await response.json();
      setIndexInfo(`Added "${data.uploaded}" — corpus now ${data.n_docs} docs / ${data.n_chunks} chunks (${data.embed_model}).`);
      loadCorpus();
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setUploading(false);
    }
  }

  async function run(q: string) {
    const trimmed = q.trim();
    if (!trimmed) return;
    setLoading(true);
    setError(null);
    try {
      const response = await fetch(`${apiBase.replace(/\/$/, "")}/api/v1/guideline-rag/run`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ question: trimmed, top_k: topK, min_score: 0.15, external_evidence: externalEvidence }),
      });
      if (!response.ok) {
        throw new Error(`HTTP ${response.status}: ${await response.text()}`);
      }
      setResult((await response.json()) as GuidelineRagResult);
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
      setResult(null);
    } finally {
      setLoading(false);
    }
  }

  return (
    <main
      style={{
        maxWidth: 860,
        margin: "0 auto",
        padding: "32px 20px 64px",
        fontFamily: "system-ui, -apple-system, Segoe UI, Roboto, sans-serif",
        color: "#0f172a",
      }}
    >
      <h1 style={{ fontSize: 24, margin: "0 0 4px" }}>Clinical Guideline RAG</h1>
      <p style={{ color: "#64748b", marginTop: 0, fontSize: 14 }}>
        Evidence-grounded answers retrieved from a clinical guideline corpus, generated by a local
        Qwen3-8B model, with a citation-faithfulness check. AI619 medical-rag team.
      </p>

      <div style={{ display: "flex", flexWrap: "wrap", gap: 8, margin: "12px 0 16px" }}>
        {EXAMPLES.map((ex) => (
          <button
            key={ex}
            onClick={() => {
              setQuestion(ex);
              run(ex);
            }}
            style={{
              fontSize: 12,
              border: "1px solid #e2e8f0",
              background: "#f8fafc",
              borderRadius: 999,
              padding: "5px 10px",
              cursor: "pointer",
              color: "#334155",
            }}
          >
            {ex.length > 52 ? ex.slice(0, 52) + "…" : ex}
          </button>
        ))}
      </div>

      <div
        style={{
          border: "1px dashed #cbd5e1",
          borderRadius: 8,
          padding: "10px 12px",
          margin: "0 0 16px",
          display: "flex",
          alignItems: "center",
          gap: 10,
          flexWrap: "wrap",
          background: "#f8fafc",
        }}
      >
        <span style={{ fontSize: 13, color: "#334155", fontWeight: 600 }}>Add to corpus:</span>
        <input
          type="file"
          accept=".md,.markdown,.txt,.text,.pdf"
          disabled={uploading}
          onChange={(e) => {
            const f = e.target.files?.[0];
            if (f) uploadDoc(f);
            e.currentTarget.value = "";
          }}
          style={{ fontSize: 13 }}
        />
        <span style={{ fontSize: 12, color: "#64748b" }}>
          {uploading ? "indexing…" : ".md / .txt / .pdf — rebuilds the FAISS index"}
        </span>
        {indexInfo ? (
          <span style={{ fontSize: 12, color: "#15803d", flexBasis: "100%" }}>✓ {indexInfo}</span>
        ) : null}
      </div>

      <div style={{ border: "1px solid #e2e8f0", borderRadius: 8, marginBottom: 16 }}>
        <button
          onClick={() => setShowCorpus((s) => !s)}
          style={{
            width: "100%",
            textAlign: "left",
            background: "#f1f5f9",
            border: "none",
            borderRadius: "8px 8px 0 0",
            padding: "8px 12px",
            cursor: "pointer",
            fontSize: 13,
            fontWeight: 600,
            color: "#334155",
            display: "flex",
            justifyContent: "space-between",
          }}
        >
          <span>{showCorpus ? "▾" : "▸"} Knowledge base — {corpus?.n_docs ?? 0} documents / {corpus?.n_chunks ?? 0} chunks</span>
          <span style={{ fontWeight: 400, color: "#64748b" }}>{corpus?.embed_model ?? ""}</span>
        </button>
        {showCorpus ? (
          <div style={{ maxHeight: 220, overflowY: "auto" }}>
            {corpus && corpus.documents.length > 0 ? (
              corpus.documents.map((doc) => (
                <div
                  key={doc.doc_id}
                  style={{
                    display: "flex",
                    justifyContent: "space-between",
                    gap: 10,
                    padding: "7px 12px",
                    borderTop: "1px solid #f1f5f9",
                    fontSize: 13,
                  }}
                >
                  <div style={{ minWidth: 0 }}>
                    <div style={{ color: "#0f172a", fontWeight: 500, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>
                      {doc.url ? (
                        <a href={doc.url} target="_blank" rel="noreferrer" style={{ color: "#1d4ed8" }}>{doc.title}</a>
                      ) : (
                        doc.title
                      )}
                    </div>
                    <div style={{ color: "#64748b", fontSize: 12 }}>{doc.source}</div>
                  </div>
                  <span style={{ color: "#64748b", fontSize: 12, whiteSpace: "nowrap" }}>{doc.n_chunks} chunks</span>
                </div>
              ))
            ) : (
              <div style={{ padding: "10px 12px", fontSize: 13, color: "#64748b" }}>
                No documents indexed yet — add one above or run the index tool.
              </div>
            )}
          </div>
        ) : null}
      </div>

      <form
        onSubmit={(e) => {
          e.preventDefault();
          run(question);
        }}
        style={{ display: "flex", flexDirection: "column", gap: 10 }}
      >
        <textarea
          value={question}
          onChange={(e) => setQuestion(e.target.value)}
          rows={2}
          placeholder="Ask a clinical question…"
          style={{
            width: "100%",
            border: "1px solid #cbd5e1",
            borderRadius: 8,
            padding: "10px 12px",
            fontSize: 15,
            resize: "vertical",
            boxSizing: "border-box",
          }}
        />
        <div style={{ display: "flex", gap: 12, alignItems: "center", flexWrap: "wrap" }}>
          <button
            type="submit"
            disabled={loading}
            style={{
              background: loading ? "#93c5fd" : "#1d4ed8",
              color: "#fff",
              border: "none",
              borderRadius: 8,
              padding: "9px 18px",
              fontSize: 14,
              fontWeight: 600,
              cursor: loading ? "default" : "pointer",
            }}
          >
            {loading ? "Retrieving…" : "Ask"}
          </button>
          <label style={{ fontSize: 13, color: "#64748b" }}>
            top_k{" "}
            <input
              type="number"
              min={1}
              max={10}
              value={topK}
              onChange={(e) => setTopK(Number(e.target.value) || 4)}
              style={{ width: 52, padding: "4px 6px", border: "1px solid #cbd5e1", borderRadius: 6 }}
            />
          </label>
          <label style={{ fontSize: 13, color: "#334155", display: "flex", alignItems: "center", gap: 5 }} title="Also fetch & merge live PubMed abstracts via the MCP gateway">
            <input
              type="checkbox"
              checked={externalEvidence}
              onChange={(e) => setExternalEvidence(e.target.checked)}
            />
            live PubMed
          </label>
          <label style={{ fontSize: 13, color: "#64748b", flex: 1, minWidth: 220 }}>
            API{" "}
            <input
              value={apiBase}
              onChange={(e) => setApiBase(e.target.value)}
              style={{
                width: "70%",
                padding: "4px 6px",
                border: "1px solid #cbd5e1",
                borderRadius: 6,
                fontSize: 12,
              }}
            />
          </label>
        </div>
      </form>

      {error ? (
        <div
          style={{
            marginTop: 16,
            background: "#fee2e2",
            border: "1px solid #fecaca",
            color: "#b91c1c",
            borderRadius: 8,
            padding: "10px 12px",
            fontSize: 13,
            whiteSpace: "pre-wrap",
          }}
        >
          {error}
        </div>
      ) : null}

      <div style={{ marginTop: 20 }}>
        <GuidelineRagCard result={result} />
      </div>
    </main>
  );
}
