"use client";

import { useState } from "react";
import { GuidelineRagCard, type GuidelineRagResult } from "../components/GuidelineRagCard";

const EXAMPLES = [
  "First-line antibiotics for a healthy adult outpatient with community-acquired pneumonia?",
  "Which first-line drug classes are recommended for stage 2 hypertension?",
  "When should an SGLT2 inhibitor be preferred over a GLP-1 receptor agonist in type 2 diabetes?",
  "What is the first-line vasopressor and MAP target in septic shock?",
];

export default function GuidelineRagPage() {
  const [apiBase, setApiBase] = useState("http://127.0.0.1:8001");
  const [question, setQuestion] = useState(EXAMPLES[0]);
  const [topK, setTopK] = useState(4);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<GuidelineRagResult | null>(null);

  async function run(q: string) {
    const trimmed = q.trim();
    if (!trimmed) return;
    setLoading(true);
    setError(null);
    try {
      const response = await fetch(`${apiBase.replace(/\/$/, "")}/api/v1/guideline-rag/run`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ question: trimmed, top_k: topK, min_score: 0.15 }),
      });
      if (!response.ok) {
        throw new Error(`HTTP ${response.status}: ${await response.text()}`);
      }
      setResult((await response.json()) as GuidelineRagResult);
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
      setResult(null);
    } finally {
      setLoading(false);
    }
  }

  return (
    <main
      style={{
        maxWidth: 860,
        margin: "0 auto",
        padding: "32px 20px 64px",
        fontFamily: "system-ui, -apple-system, Segoe UI, Roboto, sans-serif",
        color: "#0f172a",
      }}
    >
      <h1 style={{ fontSize: 24, margin: "0 0 4px" }}>Clinical Guideline RAG</h1>
      <p style={{ color: "#64748b", marginTop: 0, fontSize: 14 }}>
        Evidence-grounded answers retrieved from a clinical guideline corpus, generated by a local
        Qwen3-8B model, with a citation-faithfulness check. AI619 medical-rag team.
      </p>

      <div style={{ display: "flex", flexWrap: "wrap", gap: 8, margin: "12px 0 16px" }}>
        {EXAMPLES.map((ex) => (
          <button
            key={ex}
            onClick={() => {
              setQuestion(ex);
              run(ex);
            }}
            style={{
              fontSize: 12,
              border: "1px solid #e2e8f0",
              background: "#f8fafc",
              borderRadius: 999,
              padding: "5px 10px",
              cursor: "pointer",
              color: "#334155",
            }}
          >
            {ex.length > 52 ? ex.slice(0, 52) + "…" : ex}
          </button>
        ))}
      </div>

      <form
        onSubmit={(e) => {
          e.preventDefault();
          run(question);
        }}
        style={{ display: "flex", flexDirection: "column", gap: 10 }}
      >
        <textarea
          value={question}
          onChange={(e) => setQuestion(e.target.value)}
          rows={2}
          placeholder="Ask a clinical question…"
          style={{
            width: "100%",
            border: "1px solid #cbd5e1",
            borderRadius: 8,
            padding: "10px 12px",
            fontSize: 15,
            resize: "vertical",
            boxSizing: "border-box",
          }}
        />
        <div style={{ display: "flex", gap: 12, alignItems: "center", flexWrap: "wrap" }}>
          <button
            type="submit"
            disabled={loading}
            style={{
              background: loading ? "#93c5fd" : "#1d4ed8",
              color: "#fff",
              border: "none",
              borderRadius: 8,
              padding: "9px 18px",
              fontSize: 14,
              fontWeight: 600,
              cursor: loading ? "default" : "pointer",
            }}
          >
            {loading ? "Retrieving…" : "Ask"}
          </button>
          <label style={{ fontSize: 13, color: "#64748b" }}>
            top_k{" "}
            <input
              type="number"
              min={1}
              max={10}
              value={topK}
              onChange={(e) => setTopK(Number(e.target.value) || 4)}
              style={{ width: 52, padding: "4px 6px", border: "1px solid #cbd5e1", borderRadius: 6 }}
            />
          </label>
          <label style={{ fontSize: 13, color: "#64748b", flex: 1, minWidth: 220 }}>
            API{" "}
            <input
              value={apiBase}
              onChange={(e) => setApiBase(e.target.value)}
              style={{
                width: "70%",
                padding: "4px 6px",
                border: "1px solid #cbd5e1",
                borderRadius: 6,
                fontSize: 12,
              }}
            />
          </label>
        </div>
      </form>

      {error ? (
        <div
          style={{
            marginTop: 16,
            background: "#fee2e2",
            border: "1px solid #fecaca",
            color: "#b91c1c",
            borderRadius: 8,
            padding: "10px 12px",
            fontSize: 13,
            whiteSpace: "pre-wrap",
          }}
        >
          {error}
        </div>
      ) : null}

      <div style={{ marginTop: 20 }}>
        <GuidelineRagCard result={result} />
      </div>
    </main>
  );
}
